# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres_boilerplate:
    container_name: postgres_boilerplate_container
    build: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sql}
      POSTGRES_DB: ${POSTGRES_DB:-db_boilerplate}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres_boilerplate:${PGDATA:-/data/postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - postgres_boilerplate
    restart: unless-stopped

  pgadmin_boilerplate:
    container_name: pgadmin_boilerplate_container
    build: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-sql}
    volumes:
      - pgadmin_boilerplate:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres_boilerplate
    restart: unless-stopped

networks:
  postgres_boilerplate:
    driver: bridge

volumes:
  postgres_boilerplate:
  pgadmin_boilerplate: